### ISSUE TITLE
Feature Request: Space after English half-width symbol

### ISSUE THREAD

**Issue by oovm** [airt/pangu-rs#1]
format punctuation like

```
c,cpp,rust 等等
```

to

```
c, cpp, rust 等等
```

**Comment by airtz** [comment]
This lib is designed to be consistent with [pangu.js](https://github.com/vinta/pangu.js). Maybe we can write another lib to do this.

**Comment by oovm** [comment]
I agree, implement a markdown compatible pangu.

now `**bold**` -> `**bold **`
